---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть SPA
  - Сайт должен быть удобен на мобильных устройствах
  - В каталоге должны отображаться: название, рейтинг, цена со скидкой и без нее
  - На странице товара должны отображаться: название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления в корзину
  - На странице корзины у пользователя должна быть возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Корзина должна хранится в сессии браузера
